---
services:
  db:
    image: rineethvenkat/pylibapp:db-image
    deploy:
      replicas: 1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  auth:
    image: rineethvenkat/pylibapp:auth-image
    deploy:
      replicas: 1
    ports:
      - "5001:5001 "
    networks:
      - mynetwork
    depends_on:
      - db

  book:
    image: rineethvenkat/pylibapp:book-image
    deploy:
      replicas: 1
    ports:
      - "5002:5002"
    networks:
      - mynetwork
    depends_on:
      - db

  borrow:
    image: rineethvenkat/pylibapp:borrow-image
    deploy:
      replicas: 1
    ports:
      - "5003:5003"
    networks:
      - mynetwork
    depends_on:
      - db

  frontend:
    image: rineethvenkat/pylibapp:frontend-image
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    networks:
      - mynetwork
    depends_on:
      - auth
      - book
      - borrow

networks:
  mynetwork:
    driver: overlay
